export const topBarList = [
  { icon: 'icon-cut', value: 'cut', text: '切图(Ctrl+Q)' },
  { icon: 'icon-rect', value: 'rect', text: '框图(Ctrl+X)' },
  { icon: 'icon-text', value: 'text', text: '文字(Ctrl+E)' },
  { icon: 'icon-zoom-out', value: 'zoomIn', text: '放大(Ctrl+O)' },
  { icon: 'icon-zoom-in', value: 'zoomOut', text: '缩小(Ctrl+I)' },
  { icon: 'icon-rotate-right', value: 'rotateRight', text: '右旋转(Ctrl+R)' },
  { icon: 'icon-rotate-left', value: 'rotateLeft', text: '左旋转(Ctrl+L)' },
  // { icon: 'icon-rotate-min-right', value: 'rotateMinRight', text: '右微旋转' },
  // { icon: 'icon-rotate-min-left', value: 'rotateMinLeft', text: '左微旋转' },
  { icon: '', value: 'rotateMinLeft', name: '-5°', deg: 1, text: '5°左旋转' },
  { icon: '', value: 'rotateMinRight', name: '5°', deg: 1, text: '5°右旋转' },
  { icon: '', value: 'rotateMinLeft', name: '-10°', deg: 2, text: '10°左旋转' },
  { icon: '', value: 'rotateMinRight', name: '10°', deg: 2, text: '10°右旋转' },
  { icon: '', value: 'rotateMinLeft', name: '-15°', deg: 3, text: '15°左旋转' },
  { icon: '', value: 'rotateMinRight', name: '15°', deg: 3, text: '15°右旋转' },
  { icon: 'icon-restore', value: 'restore', text: '还原' },
  { icon: 'icon-clear', value: 'clear', text: '清除(Ctrl+Z)' },
  { icon: 'icon-done', value: 'done', text: '保存(F4)' },
  { icon: 'icon-link', value: 'link', text: '查看原图' },
]