# stronger Global Configuration


# system configuration
system:
  use-multipoint: true #是否开启Redis存jwt
  env: 'develop'  # Change to "develop" to skip authentication for development mode
  port: 9999
  common-port: 9999
  db-type: "postgres"
  name: "stronger"
  image-encrypt: true
  pro-arr: #当前服务器运行的项目
    - "B0102"
    - "B0103"
    - "B0106"
    - "B0108"
    - "B0110"
    - "B0113"
    - "B0114"
    - "B0116"
    - "B0118"
    - "B0121"
    - "B0122"
  const-url: "http://192.168.202.18:30080"
#  const-url: "http://127.0.0.1:30080"



# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# jwt configuration
jwt:
  signing-key: 'HlSys'
  expires-at: 604800  #604800

# Postgresql connect configuration
postgresql:
  username: 'postgres'
  password: 'Change.Postgres'
  host: '192.168.202.23'
  db-name: 'stronger'
  port: '5432'
  config: 'sslmode=disable TimeZone=Asia/Shanghai'
  max-idle-conns: 10
  max-open-conns: 10
  logger: true
  prefer-simple-protocol: true

# UserPostgresql connect configuration
user-db:
  username: 'postgres'
  password: 'Change.Postgres'
  host: '192.168.202.23'
  db-name: 'user_manager'
  port: '5432'
  config: 'sslmode=disable TimeZone=Asia/Shanghai'
  max-idle-conns: 10
  max-open-conns: 10
  logger: true
  prefer-simple-protocol: true

# oss configuration

# 切换本地与七牛云上传，分配头像和文件路径
localupload:
  local: true
  #file-path: D:/Projects/tempfiles/
  file-path: files/


# redis configuration
redis:
  addr: '127.0.0.1:6379'
  password: ''
  db: 0

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  expiration: 1
  gc-limit-number: 10240

# zap logger configuration
zap:
  # 可使用 "debug", "info", "warn", "error", "dpanic", "panic", "fatal",
  level: 'info'
  # console: 控制台, json: json格式输出
  format: 'console'
  prefix: '[stronger]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  # LowercaseLevelEncoder:小写, LowercaseColorLevelEncoder:小写带颜色,CapitalLevelEncoder: 大写, CapitalColorLevelEncoder: 大写带颜色,
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

#couchDB configuration
#couchdb:
#  url: 'http://admin:HL2018dbZHHLYXGS@192.168.202.13:5984/'
#  username: 'admin'
#  password: 'HL2018dbZHHLYXGS'
#  expect-url: 'http://192.168.202.13:5984'

couchdb:
  url: 'http://admin:Change.Couchdb@192.168.202.18:5984/'
  username: 'admin'
  password: 'Change.Couchdb'
  expect-url: 'http://192.168.202.18:5984'

#couchdb:
#  url: 'http://admin:admin@127.0.0.1:5984/'
#  username: 'admin'
#  password: 'admin'
#  expect-url: 'http://127.0.0.1:5984'

mongodb:
  url: mongodb://test:test@113.106.108.93:27019/?authSource=admin